# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'WindowUI.ui'
#
# Created by: PyQt5 UI code generator 5.13.0
#
# WARNING! All changes made in this file will be lost!


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(1184, 827)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.widget = GLViewWidget(self.centralwidget)
        self.widget.setGeometry(QtCore.QRect(0, 0, 921, 781))
        self.widget.setObjectName("widget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(950, 20, 47, 13))
        self.label.setObjectName("label")
        self.translateX = QtWidgets.QLineEdit(self.centralwidget)
        self.translateX.setGeometry(QtCore.QRect(950, 50, 113, 20))
        self.translateX.setObjectName("translateX")
        self.translateY = QtWidgets.QLineEdit(self.centralwidget)
        self.translateY.setGeometry(QtCore.QRect(950, 80, 113, 20))
        self.translateY.setObjectName("translateY")
        self.translateZ = QtWidgets.QLineEdit(self.centralwidget)
        self.translateZ.setGeometry(QtCore.QRect(950, 110, 113, 20))
        self.translateZ.setObjectName("translateZ")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(930, 50, 16, 16))
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(930, 80, 16, 16))
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(930, 110, 16, 16))
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setGeometry(QtCore.QRect(950, 150, 47, 13))
        self.label_5.setObjectName("label_5")
        self.rotateZ = QtWidgets.QLineEdit(self.centralwidget)
        self.rotateZ.setGeometry(QtCore.QRect(950, 240, 113, 20))
        self.rotateZ.setObjectName("rotateZ")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setGeometry(QtCore.QRect(930, 210, 16, 16))
        self.label_6.setObjectName("label_6")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setGeometry(QtCore.QRect(930, 240, 16, 16))
        self.label_7.setObjectName("label_7")
        self.rotateX = QtWidgets.QLineEdit(self.centralwidget)
        self.rotateX.setGeometry(QtCore.QRect(950, 180, 113, 20))
        self.rotateX.setObjectName("rotateX")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setGeometry(QtCore.QRect(930, 180, 16, 16))
        self.label_8.setObjectName("label_8")
        self.rotateY = QtWidgets.QLineEdit(self.centralwidget)
        self.rotateY.setGeometry(QtCore.QRect(950, 210, 113, 20))
        self.rotateY.setObjectName("rotateY")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setGeometry(QtCore.QRect(930, 310, 16, 16))
        self.label_9.setObjectName("label_9")
        self.scaleZ = QtWidgets.QLineEdit(self.centralwidget)
        self.scaleZ.setGeometry(QtCore.QRect(950, 370, 113, 20))
        self.scaleZ.setObjectName("scaleZ")
        self.scaleX = QtWidgets.QLineEdit(self.centralwidget)
        self.scaleX.setGeometry(QtCore.QRect(950, 310, 113, 20))
        self.scaleX.setObjectName("scaleX")
        self.scaleY = QtWidgets.QLineEdit(self.centralwidget)
        self.scaleY.setGeometry(QtCore.QRect(950, 340, 113, 20))
        self.scaleY.setObjectName("scaleY")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setGeometry(QtCore.QRect(950, 280, 47, 13))
        self.label_10.setObjectName("label_10")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setGeometry(QtCore.QRect(930, 370, 16, 16))
        self.label_11.setObjectName("label_11")
        self.label_12 = QtWidgets.QLabel(self.centralwidget)
        self.label_12.setGeometry(QtCore.QRect(930, 340, 16, 16))
        self.label_12.setObjectName("label_12")
        self.label_13 = QtWidgets.QLabel(self.centralwidget)
        self.label_13.setGeometry(QtCore.QRect(1070, 180, 47, 13))
        self.label_13.setObjectName("label_13")
        self.label_14 = QtWidgets.QLabel(self.centralwidget)
        self.label_14.setGeometry(QtCore.QRect(1070, 210, 47, 13))
        self.label_14.setObjectName("label_14")
        self.label_15 = QtWidgets.QLabel(self.centralwidget)
        self.label_15.setGeometry(QtCore.QRect(1070, 240, 47, 13))
        self.label_15.setObjectName("label_15")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(970, 440, 181, 23))
        self.pushButton.setObjectName("pushButton")
        self.label_16 = QtWidgets.QLabel(self.centralwidget)
        self.label_16.setGeometry(QtCore.QRect(950, 640, 201, 141))
        self.label_16.setObjectName("label_16")
        self.scaleAll = QtWidgets.QLineEdit(self.centralwidget)
        self.scaleAll.setGeometry(QtCore.QRect(970, 400, 113, 20))
        self.scaleAll.setObjectName("scaleAll")
        self.label_17 = QtWidgets.QLabel(self.centralwidget)
        self.label_17.setGeometry(QtCore.QRect(930, 400, 41, 16))
        self.label_17.setObjectName("label_17")
        self.resetButton = QtWidgets.QPushButton(self.centralwidget)
        self.resetButton.setGeometry(QtCore.QRect(970, 470, 181, 23))
        self.resetButton.setObjectName("resetButton")
        self.projectionButton = QtWidgets.QPushButton(self.centralwidget)
        self.projectionButton.setGeometry(QtCore.QRect(970, 500, 181, 23))
        self.projectionButton.setObjectName("projectionButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 1184, 21))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Translate"))
        self.label_2.setText(_translate("MainWindow", "x"))
        self.label_3.setText(_translate("MainWindow", "y"))
        self.label_4.setText(_translate("MainWindow", "z"))
        self.label_5.setText(_translate("MainWindow", "Rotate"))
        self.label_6.setText(_translate("MainWindow", "y"))
        self.label_7.setText(_translate("MainWindow", "z"))
        self.label_8.setText(_translate("MainWindow", "x"))
        self.label_9.setText(_translate("MainWindow", "x"))
        self.label_10.setText(_translate("MainWindow", "Scale"))
        self.label_11.setText(_translate("MainWindow", "z"))
        self.label_12.setText(_translate("MainWindow", "y"))
        self.label_13.setText(_translate("MainWindow", "degrees"))
        self.label_14.setText(_translate("MainWindow", "degrees"))
        self.label_15.setText(_translate("MainWindow", "degrees"))
        self.pushButton.setText(_translate("MainWindow", "Perform transformations"))
        self.label_16.setText(_translate("MainWindow", "<html><head/><body><p>Legend:</p><p>X Axis - blue line</p><p>Y Axis - yellow line</p><p>Z Axis - green line</p><p>Grid cell size: 10</p></body></html>"))
        self.label_17.setText(_translate("MainWindow", "all axis"))
        self.resetButton.setText(_translate("MainWindow", "Reset"))
        self.projectionButton.setText(_translate("MainWindow", "Toggle projections"))
from pyqtgraph.opengl import GLViewWidget


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
